name: Publish package to npmjs registry
on:
  release:
    types: [created]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm test
      - run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}